"""
hook_generator.py — Phase 2: Frida Hook Script Generator.

Takes the structured JSON findings from static_analysis.py and auto-generates
a Frida JavaScript hook script targeting the specific suspicious methods/classes
found during static analysis.

The MVP does NOT execute hooks — it writes the .js file and prints
instructions for manual execution:
    frida -U -f <package> -l <script.js>

Usage (programmatic):
    generator = HookGenerator(findings, app_package="com.example.app")
    script_path = generator.generate(output_dir=Path("reports"))

Usage (CLI):
    Called from triage.py — do not run this file directly.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from utils import console, get_logger

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Frida JS Hook Templates
# ---------------------------------------------------------------------------

# Each template is a Python f-string. Placeholders:
#   {class_name}   – Java class (dot-separated, e.g. javax.crypto.Cipher)
#   {method_name}  – Method name
#   {finding_id}   – Finding ID for reference
#   {evidence}     – Raw evidence string from the finding

_HOOK_HEADER = """\
// =============================================================
// Frida Hook Script — Auto-generated by Mobile App Security Triage Engine
// Package : {package}
// Generated: {timestamp}
//
// Usage:
//   frida -U -f {package} -l {script_name} --no-pause
//   frida -U --attach-name {package} -l {script_name}
//
// IMPORTANT: For defensive/research use only on apps you own
//            or have explicit written permission to test.
// =============================================================

"use strict";

Java.perform(function () {{
"""

_HOOK_FOOTER = """\
  console.log("[*] All hooks installed.");
}});
"""

_TEMPLATE_WEAK_CRYPTO = """\
  // [{finding_id}] Weak crypto: {evidence}
  try {{
    var MessageDigest = Java.use("{class_name}");
    var orig_getInstance = MessageDigest.getInstance.overload("java.lang.String");
    orig_getInstance.implementation = function (algorithm) {{
      console.log("[CRYPTO] {class_name}.getInstance called with: " + algorithm);
      var result = orig_getInstance.call(this, algorithm);
      return result;
    }};
    console.log("[+] Hooked {class_name}.getInstance");
  }} catch (e) {{
    console.log("[-] Failed to hook {class_name}.getInstance: " + e);
  }}
"""

_TEMPLATE_CIPHER = """\
  // [{finding_id}] Cipher usage: {evidence}
  try {{
    var Cipher = Java.use("javax.crypto.Cipher");
    var orig_getInstance = Cipher.getInstance.overload("java.lang.String");
    orig_getInstance.implementation = function (transformation) {{
      console.log("[CIPHER] Cipher.getInstance called with: " + transformation);
      var result = orig_getInstance.call(this, transformation);
      return result;
    }};
    // Also hook doFinal to capture plaintext/ciphertext
    Cipher.doFinal.overload("[B").implementation = function (input) {{
      console.log("[CIPHER] doFinal input (hex): " + bytesToHex(input));
      var result = this.doFinal(input);
      console.log("[CIPHER] doFinal output (hex): " + bytesToHex(result));
      return result;
    }};
    console.log("[+] Hooked javax.crypto.Cipher");
  }} catch (e) {{
    console.log("[-] Failed to hook Cipher: " + e);
  }}
"""

_TEMPLATE_EXPORTED_ACTIVITY = """\
  // [{finding_id}] Exported Activity (no permission guard): {class_name}
  try {{
    var Activity = Java.use("{class_name}");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {{
      console.log("[ACTIVITY] {class_name}.onCreate called");
      if (bundle !== null) {{
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }}
      this.onCreate(bundle);
    }};
    console.log("[+] Hooked {class_name}.onCreate");
  }} catch (e) {{
    console.log("[-] Failed to hook {class_name}: " + e);
  }}
"""

_TEMPLATE_HTTP_CLEARTEXT = """\
  // [{finding_id}] Cleartext HTTP traffic: {evidence}
  try {{
    var URL = Java.use("java.net.URL");
    URL.$init.overload("java.lang.String").implementation = function (url) {{
      if (url && url.startsWith("http://")) {{
        console.log("[HTTP] Cleartext URL constructed: " + url);
        // Print a stack trace to find the caller
        console.log(Java.use("android.util.Log").getStackTraceString(
          Java.use("java.lang.Exception").$new("stack trace")
        ));
      }}
      return this.$init(url);
    }};
    console.log("[+] Hooked java.net.URL for cleartext detection");
  }} catch (e) {{
    console.log("[-] Failed to hook URL: " + e);
  }}
"""

_TEMPLATE_GENERIC = """\
  // [{finding_id}] {title} — manual hook needed
  // Evidence: {evidence}
  // Location: {location}
  // TODO: Add a specific Frida hook for this finding.
"""

_HELPER_BYTES_TO_HEX = """\
  // --- Utility: bytes → hex string ---
  function bytesToHex(bytes) {
    if (!bytes) return "null";
    var hex = "";
    for (var i = 0; i < bytes.length; i++) {
      hex += ("0" + (bytes[i] & 0xFF).toString(16)).slice(-2);
    }
    return hex;
  }

"""


class HookGenerator:
    """Generates Frida hook scripts from static analysis findings.

    Attributes:
        findings:    List of finding dicts from APKAnalyzer.run_full_analysis().
        app_package: Android package name (e.g. 'com.example.app').
        verbose:     Enable debug logging.
    """

    def __init__(
        self,
        findings: list[dict[str, Any]],
        app_package: str,
        verbose: bool = False,
    ) -> None:
        self.findings = findings
        self.app_package = app_package
        self.verbose = verbose

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, output_dir: Path) -> Path:
        """Generate a Frida hook script and write it to *output_dir*.

        Args:
            output_dir: Directory to write the .js file into.

        Returns:
            Path to the generated script file.
        """
        from datetime import datetime

        output_dir.mkdir(parents=True, exist_ok=True)
        safe_pkg = self.app_package.replace(".", "_")
        script_name = f"{safe_pkg}_hooks.js"
        script_path = output_dir / script_name

        hooks = self._build_hooks()

        if not hooks:
            console.print(
                "[dim]  No actionable findings for Frida hooks — "
                "no hook script generated.[/dim]"
            )
            return script_path  # Return path even if empty

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        header = _HOOK_HEADER.format(
            package=self.app_package,
            timestamp=timestamp,
            script_name=script_name,
        )

        script_content = header + _HELPER_BYTES_TO_HEX + "\n".join(hooks) + "\n" + _HOOK_FOOTER

        script_path.write_text(script_content, encoding="utf-8")

        # Print usage instructions
        console.rule("[bold blue]Frida Hook Script Generated[/bold blue]")
        console.print(f"\n[info]✔ Script written to:[/info] {script_path}\n")
        console.print("  [bold]To run manually:[/bold]")
        console.print(
            f"  [dim]# Spawn mode (restarts the app):[/dim]\n"
            f"  frida -U -f [bold]{self.app_package}[/bold] -l {script_path} --no-pause\n\n"
            f"  [dim]# Attach mode (app already running):[/dim]\n"
            f"  frida -U --attach-name [bold]{self.app_package}[/bold] -l {script_path}\n"
        )
        console.print(f"  [dim]Hooks generated for {len(hooks)} finding(s).[/dim]\n")

        return script_path

    # ------------------------------------------------------------------
    # Internal: Hook Builder
    # ------------------------------------------------------------------

    def _build_hooks(self) -> list[str]:
        """Map each finding to its Frida JS hook snippet.

        Returns:
            List of JS hook string snippets (no header/footer).
        """
        hooks: list[str] = []
        seen_hooks: set[str] = set()  # Avoid duplicate hooks for same class/method

        for finding in self.findings:
            ftype = finding.get("type", "")
            fid = finding.get("id", "???")
            evidence = finding.get("evidence", "")
            location = finding.get("location", "")
            title = finding.get("title", "")
            algo = finding.get("algorithm", "")

            hook = None

            if ftype == "weak_crypto":
                # Determine the class to hook based on algorithm
                if algo in {"MD5", "SHA-1", "SHA1"}:
                    class_name = "java.security.MessageDigest"
                else:
                    class_name = "javax.crypto.Cipher"

                dedup = f"crypto:{class_name}"
                if dedup not in seen_hooks:
                    seen_hooks.add(dedup)
                    if class_name == "java.security.MessageDigest":
                        hook = _TEMPLATE_WEAK_CRYPTO.format(
                            finding_id=fid,
                            evidence=evidence,
                            class_name=class_name,
                        )
                    else:
                        hook = _TEMPLATE_CIPHER.format(
                            finding_id=fid,
                            evidence=evidence,
                        )

            elif ftype == "exported_component_no_permission":
                comp_type = finding.get("component_type", "")
                class_name = location  # location holds the FQCN
                if comp_type == "Activity":
                    dedup = f"activity:{class_name}"
                    if dedup not in seen_hooks:
                        seen_hooks.add(dedup)
                        hook = _TEMPLATE_EXPORTED_ACTIVITY.format(
                            finding_id=fid,
                            class_name=class_name.replace("/", ".").strip("L;"),
                            evidence=evidence,
                        )

            elif ftype in ("cleartext_traffic_enabled", "nsc_cleartext_permitted",
                           "nsc_domain_cleartext_permitted"):
                dedup = "http:cleartext"
                if dedup not in seen_hooks:
                    seen_hooks.add(dedup)
                    hook = _TEMPLATE_HTTP_CLEARTEXT.format(
                        finding_id=fid,
                        evidence=evidence,
                    )

            elif ftype in ("hardcoded_secret", "hardcoded_secret_java"):
                # Secrets are static findings — no runtime hook needed at this level.
                # Generate a placeholder comment for the analyst.
                hook = _TEMPLATE_GENERIC.format(
                    finding_id=fid,
                    title=title,
                    evidence=evidence[:80],
                    location=location,
                )

            if hook:
                hooks.append(hook)

        return hooks
