// =============================================================
// Frida Hook Script — Auto-generated by Mobile App Security Triage Engine
// Package : com.android.insecurebankv2
// Generated: 2026-09-05 18:40:19
//
// Usage:
//   frida -U -f com.android.insecurebankv2 -l com_android_insecurebankv2_hooks.js --no-pause
//   frida -U --attach-name com.android.insecurebankv2 -l com_android_insecurebankv2_hooks.js
//
// IMPORTANT: For defensive/research use only on apps you own
//            or have explicit written permission to test.
// =============================================================

"use strict";

Java.perform(function () {
  // --- Utility: bytes → hex string ---
  function bytesToHex(bytes) {
    if (!bytes) return "null";
    var hex = "";
    for (var i = 0; i < bytes.length; i++) {
      hex += ("0" + (bytes[i] & 0xFF).toString(16)).slice(-2);
    }
    return hex;
  }

  // [EXPORT_001] Exported Activity (no permission guard): com.android.insecurebankv2.ViewStatement
  try {
    var Activity = Java.use("com.android.insecurebankv2.ViewStatement");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {
      console.log("[ACTIVITY] com.android.insecurebankv2.ViewStatement.onCreate called");
      if (bundle !== null) {
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }
      this.onCreate(bundle);
    };
    console.log("[+] Hooked com.android.insecurebankv2.ViewStatement.onCreate");
  } catch (e) {
    console.log("[-] Failed to hook com.android.insecurebankv2.ViewStatement: " + e);
  }

  // [EXPORT_002] Exported Activity (no permission guard): com.android.insecurebankv2.ChangePassword
  try {
    var Activity = Java.use("com.android.insecurebankv2.ChangePassword");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {
      console.log("[ACTIVITY] com.android.insecurebankv2.ChangePassword.onCreate called");
      if (bundle !== null) {
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }
      this.onCreate(bundle);
    };
    console.log("[+] Hooked com.android.insecurebankv2.ChangePassword.onCreate");
  } catch (e) {
    console.log("[-] Failed to hook com.android.insecurebankv2.ChangePassword: " + e);
  }

  // [EXPORT_003] Exported Activity (no permission guard): com.android.insecurebankv2.LoginActivity
  try {
    var Activity = Java.use("com.android.insecurebankv2.LoginActivity");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {
      console.log("[ACTIVITY] com.android.insecurebankv2.LoginActivity.onCreate called");
      if (bundle !== null) {
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }
      this.onCreate(bundle);
    };
    console.log("[+] Hooked com.android.insecurebankv2.LoginActivity.onCreate");
  } catch (e) {
    console.log("[-] Failed to hook com.android.insecurebankv2.LoginActivity: " + e);
  }

  // [EXPORT_004] Exported Activity (no permission guard): com.android.insecurebankv2.PostLogin
  try {
    var Activity = Java.use("com.android.insecurebankv2.PostLogin");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {
      console.log("[ACTIVITY] com.android.insecurebankv2.PostLogin.onCreate called");
      if (bundle !== null) {
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }
      this.onCreate(bundle);
    };
    console.log("[+] Hooked com.android.insecurebankv2.PostLogin.onCreate");
  } catch (e) {
    console.log("[-] Failed to hook com.android.insecurebankv2.PostLogin: " + e);
  }

  // [EXPORT_005] Exported Activity (no permission guard): com.android.insecurebankv2.DoTransfer
  try {
    var Activity = Java.use("com.android.insecurebankv2.DoTransfer");
    Activity.onCreate.overload("android.os.Bundle").implementation = function (bundle) {
      console.log("[ACTIVITY] com.android.insecurebankv2.DoTransfer.onCreate called");
      if (bundle !== null) {
        console.log("[ACTIVITY] Intent extras: " + bundle.toString());
      }
      this.onCreate(bundle);
    };
    console.log("[+] Hooked com.android.insecurebankv2.DoTransfer.onCreate");
  } catch (e) {
    console.log("[-] Failed to hook com.android.insecurebankv2.DoTransfer: " + e);
  }

  // [SECRET_001] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://goo.gl/8Rd3yj
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_002] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://goo.gl/naFqQk
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_003] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://plus.google.com/
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_004] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/ActivateAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_005] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/ActiveActionStatus
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_006] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/AddAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_007] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/BookmarkAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_008] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/CommunicateAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_009] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/CompletedActionStatus
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_010] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/FailedActionStatus
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_011] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/FilmAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_012] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/LikeAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_013] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/ListenAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_014] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/PhotographAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_015] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/ReserveAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_016] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/SearchAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_017] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/ViewAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_018] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/WantAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_019] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schema.org/WatchAction
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_020] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://schemas.android.com/apk/lib/com.google.android.gms.pl…
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_021] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://www.google-analytics.com
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  // [SECRET_022] Potential hardcoded secret: Hardcoded URL (HTTP) — manual hook needed
  // Evidence: http://www.google.com
  // Location: DEX string constants
  // TODO: Add a specific Frida hook for this finding.

  console.log("[*] All hooks installed.");
}});
